[package]
name = "cf-base"
version = "1.0.0"
description = "CoinFlip types, messages, states and utils"
repository = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
cw20-base = { workspace = true }
cw721 = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
hashing-helper = { workspace = true }
