import { ChainConfig } from "../../common/interfaces";
import { $, toJson } from "./config-utils";
import * as PlatformTypes from "../codegen/Platform.types";

export type NetworkName = "MANTRA";

export type Wasm = "platform.wasm";

export type Label = "platform";

export const ADDRESS = {
  MAINNET: {
    MANTRA: {
      ADMIN: "mantra1f37v0rdvrred27tlqqcpkrqpzfv6ddr2zjrm2h",
      WORKER: "mantra1hvp3q00ypzrurd46h7c7c3hu86tx9uf80lfxn6",
    },
  },
  TESTNET: {
    MANTRA: {
      ADMIN: "mantra1f37v0rdvrred27tlqqcpkrqpzfv6ddr2zjrm2h",
      WORKER: "mantra1hvp3q00ypzrurd46h7c7c3hu86tx9uf80lfxn6",
    },
  },
};

export const TOKEN = {
  MANTRA: {
    MAINNET: {
      OM: "uom",
    },
    TESTNET: {
      OM: "uom",
    },
  },
};

/**
 * This config is used to generate `config.json` used by any script (ts, js, bash).
 * It must be filled manually. If any contract must be added it's required to include
 * it with default parameters - code is 0, address is "".
 * This config uses logs.json generated by local-interchaintest to update endpoints
 * in cofig.json.
 */
export const CHAIN_CONFIG: ChainConfig = {
  CHAINS: [
    {
      NAME: "mantra",
      PREFIX: "mantra",
      OPTIONS: [
        // TODO: MANTRA test
        {
          TYPE: "test",
          DENOM: "uom",
          CHAIN_ID: "mantra-dukong-1",
          RPC_LIST: [
            "https://rpc.dukong.mantrachain.io:443",
            "https://mantra-testnet-rpc.publicnode.com:443",
          ],
          GAS_PRICE_AMOUNT: 0.02,
          STORE_CODE_GAS_MULTIPLIER: 115,
          CONTRACTS: [
            {
              WASM: "platform.wasm",
              LABEL: "platform",
              PERMISSION: [ADDRESS.TESTNET.MANTRA.ADMIN],
              INIT_MSG: toJson<PlatformTypes.InstantiateMsg>({
                bet: { min: `${500_000}`, max: `${10_000_000}` },
              }),
              MIGRATE_MSG: toJson<PlatformTypes.MigrateMsg>({
                version: "1.0.0",
              }),
              UPDATE_MSG: toJson<PlatformTypes.ExecuteMsg>({
                update_config: {},
              }),
              CODE: 365,
              ADDRESS:
                "mantra17gc3eztg9xk7w7fkx0525c6jt0et2aapkfpca5xf5txkdwc68y8q4teya8",
            },
          ],
          IBC: [],
        },
      ],
    },
  ],
};
