/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type Decimal = string;
export interface InstantiateMsg {
  bet?: Range | null;
  platform_fee?: Decimal | null;
  worker?: string | null;
}
export interface Range {
  max: Uint128;
  min: Uint128;
}
export type ExecuteMsg = {
  flip: {
    side: Side;
  };
} | {
  claim: {};
} | {
  accept_admin_role: {};
} | {
  deposit: {};
} | {
  withdraw: {
    amount: Uint128;
    recipient?: string | null;
  };
} | {
  update_config: {
    admin?: string | null;
    bet?: Range | null;
    platform_fee?: Decimal | null;
    worker?: string | null;
  };
} | {
  pause: {};
} | {
  unpause: {};
};
export type Side = "head" | "tail";
export type QueryMsg = {
  config: {};
} | {
  app_info: {};
} | {
  required_to_deposit: {};
} | {
  available_to_withdraw: {};
} | {
  user: {
    address: string;
  };
} | {
  user_list: {
    amount: number;
    start_after?: string | null;
  };
};
export interface MigrateMsg {
  version: string;
}
export type SignedDecimal = string;
export type Int256 = string;
export interface AppInfo {
  average_fee: SignedDecimal;
  balance: Uint128;
  deposited: Uint128;
  revenue: Revenue;
  user_stats: Stats;
  user_unclaimed: Uint128;
}
export interface Revenue {
  current: Int256;
  total: Int256;
}
export interface Stats {
  bets: StatsItem;
  wins: StatsItem;
}
export interface StatsItem {
  count: number;
  value: Uint128;
}
export type Addr = string;
export interface Config {
  admin: Addr;
  bet: Range;
  denom: string;
  platform_fee: Decimal;
  worker?: Addr | null;
}
export interface UserInfo {
  last_flip_date: number;
  roi: SignedDecimal;
  stats: Stats;
  unclaimed: Uint128;
}
export type ArrayOfUserListRespItem = UserListRespItem[];
export interface UserListRespItem {
  address: Addr;
  info: UserInfo;
}